Tests of basic functions for boundary operators and combinatorial laplacian.

In [118]:
import numpy as np
import itertools as it
from scipy.sparse import csr_matrix

import backend.np_backend as be
import numpy as np

### Get boundary operator as sparse crs matrix

In [119]:
mat = be.boundary_operator_crsmat(3).toarray()
mat

array([[ 0,  1,  1,  0,  1,  0,  0,  0],
       [ 0,  0,  0, -1,  0, -1,  0,  0],
       [ 0,  0,  0,  1,  0,  0, -1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  1,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

### Check, that $\partial^2 = 0$

In [120]:
mat@mat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

### Example boundary is calculated.

In [121]:
state = [(1,1,0,1,0,0,1)]
n_vertices = len(state[0])
mat = be.boundary_operator_crsmat(n_vertices).toarray()
vec = be.state_to_vec(state)
vec_to_state(mat@vec)

{(0, 1, 0, 1, 0, 0, 1): -1.0,
 (1, 0, 0, 1, 0, 0, 1): 1.0,
 (1, 1, 0, 0, 0, 0, 1): -1.0,
 (1, 1, 0, 1, 0, 0, 0): 1.0}

### Combinatorial laplacian of order $k$

In [122]:
k = 2
n_vertices = 3
mat = be.combinatorial_laplacian(3, 2)
mat.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])